### ISSUE TITLE
Figure out how to have MSes post to our app for true between-MSes architecture

### ISSUE THREAD

**Issue by joepav** [oslabs-beta/Interspect#66] opened 2019-06-17 19:32 UTC
We should find out how our app can accept post requests from microservice A so the developer doesn't need to build out an API when posting the output of microservice A.  Then users will have two options, get requests (to something like the Yelp API) and accepting post requests between microservices.

**Comment by conor-jh** [comment] 2019-06-25 15:43
Duplicate of #71

**Closed as completed by conor-jh** 2019-06-25 15:43 UTC
